
### 共通変数
@host = http://localhost:5000/api/v1
@id = dotart
@password = dotart

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcklkIjoiZG90YXJ0IiwibmFtZSI6ImFkbWluIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2MzQ3OTkwODksImV4cCI6MTYzNDgwMDI4OX0.FAkgRzsoa-kDgr8_IzFr403TcbxB9k_YWEmHv5gDNRI

@emailToken = 28787557

@passwordToken = JDJiJDEwJGlEZHRaOHdaTXk1REtCUlZQL2x5RE9UNkdaNU5vamkuZ2RvMDVtcy5vVE1rY3JxOWZyZi5L

### レスポンステスト

GET {{host}} HTTP/1.1

### Emali認証

POST {{host}}/{{emailToken}}/confirm HTTP/1.1
Content-Type: application/json

{}

### アカウント登録

POST {{host}}/signup HTTP/1.1
Content-Type: application/json

{
    "userId": "{{id}}",
    "name": "admin",
    "email": "info@dot.art",
    "password": "{{password}}"
}

### ログイン

POST {{host}}/login HTTP/1.1
Content-Type: application/json
# userId: {{id}}
# password: {{password}}

{
    "userId": "{{id}}",
    "password": "{{password}}"
}

### ログアウト

POST {{host}}/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{}

### 認証付きページのテスト

GET {{host}}/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{}

### パスワードリセットリクエスト

POST {{host}}/passwordResetReq HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{}

### パスワードリセット

POST {{host}}/{{passwordToken}}/passwordReset HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "password": "{{password}}"
}

### all user fetch

GET {{host}}/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{}