
### 共通変数
@host = http://localhost:5000/api/v1
@id = dotart
@password = dotart

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcklkIjoiZG90YXJ0IiwibmFtZSI6ImFkbWluIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2MzQzOTY5NTAsImV4cCI6MTYzNDM5ODE1MH0.hKvHvcsOCqqdGqQSROIFN3NdAWO55aHdv4q5yo-1yaQ

@emailToken = 87213817

### レスポンステスト

GET {{host}} HTTP/1.1

### Emali認証

POST {{host}}/{{emailToken}}/confirm HTTP/1.1
Content-Type: application/json

{}

### アカウント登録

POST {{host}}/signup HTTP/1.1
Content-Type: application/json

{
    "userId": "{{id}}",
    "name": "admin",
    "email": "info@dot.art",
    "password": "{{password}}"
}

### ログイン

POST {{host}}/login HTTP/1.1
Content-Type: application/json
# userId: {{id}}
# password: {{password}}

{
    "userId": "{{id}}",
    "password": "{{password}}"
}

### ログアウト

POST {{host}}/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{}

### 認証付きページのテスト

GET {{host}}/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userId": "{{id}}"
}